
rabbitmqmaster:
  #image: tutum/rabbitmq
  build: ./tutum-docker-rabbitmq
  environment:
    - RABBITMQ_PASS=admin
  ports:
    - "15672:15672"

mongodb:
  image: mongo
  ports:
    - "27017:27017"


